[package]
name = "bean_bot"
version = "0.1.0"
authors = ["Rasmus Lyxell", "Filip Henningsson", "Mimmi Edholm"]
edition = "2018"

[dependencies]
serenity = "0.10"
tokio = { version = "1", features = ["full"] }