[package]
name = "bean_bot"
version = "0.1.0"
authors = ["Rasmus Lyxell", "Filip Henningsson", "Mimmi Edholm"]
edition = "2018"

[dependencies]
serenity = {version = "0.10", default-features = false, features = ["client", "gateway", "rustls_backend", "model"]}
tokio = { version = "1", features = ["full"] }