[package]
name = "bean_bot"
version = "0.1.1"
authors = ["Rasmus Lyxell", "Filip Henningsson", "Mimmi Edholm"]
edition = "2018"

[dependencies]
markov = "1.1.0"
serenity = "0.10.4"
tokio = { version = "1", features = ["full"] }
rusqlite = {version = "0.24.2", features=["bundled"]}