[package]
name = "bean_bot"
version = "0.1.3"
authors = ["Rasmus Lyxell", "Filip Henningsson", "Mimmi Edholm"]
edition = "2018"

[dependencies]
serenity = "0.10.4"
tokio = { version = "1", features = ["full"] }
rusqlite = {version = "0.24.2", features=["bundled", "chrono"]}
rand = "0.8"
chrono = "0.4"